### ISSUE TITLE
Tableview don't work didSelectRowAt indexPath when i tap on img

### ISSUE THREAD

**Issue by muaviya** [MillmanY/MMPlayerView#39]
I use example MMPlayerView. I have `didSelectRowAt indexPath`, but this don't work. Before MMPlayerView `didSelectRowAt indexPath`  worked. For show video I use `    @IBOutlet weak var imgVideo: UIImageView!`  in  `class UITableViewCell`

then I tried  did next: 

`        let tapVideoImgGesture = UITapGestureRecognizer(target: self, action: #selector(tapOnVideoImg(tapGestureRecognizer:)))
        imgVideo.isUserInteractionEnabled = true
        imgVideo.addGestureRecognizer(tapVideoImgGesture)`

` @objc func tapOnVideoImg(tapGestureRecognizer: UITapGestureRecognizer){
              print("tap video image")
    }`

the above code does not work

**Comment by MandeepSingh1** [comment]
Because When you implement the MMPlayer View, they have tap gesture code inside his MMPlayerLayer Class. So when ever you tap on did select of your tableview,  tap gesture of MMPlayerLayer will call. So thats why your did select is not working. So If you want your did select will work.

You have to do follwing Steps:-
1. Open MMPlayerLayer Class, Search the _playView in that class. And they are adding the tap gesture onto the _playView like the below.
new.addGestureRecognizer(tapGesture)
2. Just Comment the above line. And after that your did select will be working again.

Cheers!
