### ISSUE TITLE
iOS13 fatal exception: NSRangeException

### ISSUE THREAD

**Issue by xvicient21** [MillmanY/MMPlayerView#74]
Hi,

We are having an issue on iOS 13:

```
MMPlayerView | MMPlayerItem.swift line 44
MMPlayerItem.__deallocating_deinit + 44
```

```
Fatal Exception: NSRangeException
Cannot remove an observer <_NSKeyValueObservation 0x281f48c40> for the key path "status" from <MMPlayerView.MMPlayerItem 0x28077b980> because it is not registered as an observer.
MMPlayerItem.__deallocating_deinit
```

Are you aware of it?

Thx!

**Comment by MillmanY** [comment]
Hi, I fixed on pod '5.0.9', try again!!

**Comment by xvicient21** [comment]
Hi, have you deprecated iOS 11 too? Right now the library only supports one production version, iOS 12...

**Comment by MillmanY** [comment]
I think support two version (ios12,13) is enough

**Comment by mohit196** [comment]
I am using 5.1.1

I am getting an error on playing new video: 
Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <_NSKeyValueObservation 0x282f08450> for the key path "status" from <MMPlayerView.MMPlayerItem 0x2837a6400> because it is not registered as an observer.'

Are you aware of it?

Thanks
